/*
   This file was generated automatically by the Mojo IDE version B1.3.4.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift_5 (
    input [7:0] a,
    input [7:0] b,
    input [1:0] slct,
    output reg [7:0] out
  );
  
  
  
  reg [23:0] result;
  
  always @* begin
    result = 24'h000000;
    
    case (slct)
      2'h0: begin
        out = a << b[0+3-:4];
      end
      2'h1: begin
        out = a >> b[0+3-:4];
      end
      2'h3: begin
        out = $signed(a) >>> b[0+3-:4];
      end
      default: begin
        out = a;
      end
    endcase
  end
endmodule
